server:
  port: 9000

spring:
  application:
    name: SCW-ORDER
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/atcrowdfunding?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    filters: stat  #开启监控过滤器
  redis:
    host: 192.168.188.137
    password: 123456
    port: 6379

mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:com/muxin/project/mapper/*.xml

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    appname: SCW-ORDER
    prefer-ip-address: true

logging:
  file:
    path: E:\idea\IdeaProjects\qiyi-parent\scw-parent\scw-order\src\main\resources\log\scw-order
  level:
    com:
      muxin: debug