server:
  port: 8000

spring:
  application:
    name: SCW-PROJECT
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/atcrowdfunding?serverTimezone=GMT%2B8&useSSL=false&useUnicode=true&characterEncoding=UTF-8
  redis:
    host: 192.168.188.135
    password: 123456
    port: 6379

mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:com/muxin/project/mapper/*.xml

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    appname: SCW-PROJECT
    prefer-ip-address: true

logging:
  file:
    path: E:\idea\IdeaProjects\qiyi-parent\scw-parent\scw-project\src\main\resources\log\scw-project
  level:
    com:
      muxin: debug

oss:
  endpoint: http://oss-cn-beijing.aliyuncs.com
  bucketDomain: qiy.oss-cn-beijing.aliyuncs.com
  accessKeyId: LTAI4GJJ4UBqwKS1E1Dw7toU
  accessKeySecret: BKJeQ091J4qTCHVWf5U0c0Ft9wvaiY
  bucketName: qiy
